version: '3.1'

services:
  db: 
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgres/data
  nginx:
    image: nginx:lastest
    container_name: nginx
    ports: 
      - 80:80
    volumes:
      ./nginx.conf:/etc/nginx/nginx.conf:ro
