version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000

    depends_on: 
      - db
    restart: always
  db: 
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgres/data
  nginx:
    image: nginx:latest
    container_name: nginx
    ports: 
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - app
    restart: always
