version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000

    depends_on: 
      - db
    restart: always
  websocket:
    build:
      context: ./services/websocket/
      dockerfile: Dockerfile
    ports:
      - 4001:4001
  nginx:
    image: nginx:latest
    container_name: nginx
    ports: 
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - app
    restart: always
